### ISSUE TITLE
no longer works (at all)

### ISSUE THREAD

**Issue by illtellyoulater** [darrinhenein/VerticalTabs#27]
It doesn't work with newer firefox versions, all you will see is the vertical tabs pane using up all the screen.

**Comment by ignlg** [comment]
It works nicely on my Firefox 36.0.4 over Mac OS X Mavericks 10.9.5

**Comment by illtellyoulater** [comment]
It didn't when I tried it on 36.0 or 36.0.1 (can't remember which, or if both). Since I needed an alternative fast I switched to Pano (https://github.com/teramako/Pano).

**Comment by illtellyoulater** [comment]
I tried it again on 36.0.4 and then 37.0.1. Same thing. I am starting to thing that this might be the effect of some kind of settings leftovers by the older versions of verticaltabs I tried maybe...

**Comment by illtellyoulater** [comment]
I restored Firefox to initial state using the troubleshooting in the help menu and the problem is gone. This version of verticaltabs is now working as expected to me on Firefox 37.0.1.
Thanks.
